version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql_spring_boot2
    environment:
      MYSQL_ROOT_PASSWORD: raiz123
    ports:
    - "3306:3306"
    volumes:
    - devdojo_data:/var/lib/mysql

volumes:
  devdojo_data: