server:
  error:
    include-stacktrace: ON_PARAM

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?&createDatabaseIfNotExist=true
    username: root
    password: raiz123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
